version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user@123
      POSTGRES_DB: amazon_db